In [184]:
## read the fuquan combine data
from package_path_define.path_define import *
from package_readdata.read_fuquan_combine import *

stk_num="000917"
df1=read_fuquan_combine(stk_num)
df2=df1.sort_values(by=['date'])
data_df1=df2.reset_index(drop=True) ## get data by date
print data_df1.head()
print len(data_df1)

G:\\stock\\data\fuquan_combine\shenzhen\000917_fuquan_all.csv
         date   open   high  close    low      volume  trade_amount  \
0  1999-03-25  19.01  20.38  18.99  18.90  32064800.0   629395704.0   
1  1999-03-26  18.90  19.46  18.26  18.02   8322600.0   156266563.0   
2  1999-03-29  18.20  18.47  18.01  17.71   3945300.0    70956198.0   
3  1999-03-30  18.05  18.55  18.29  17.75   2168600.0    39468139.0   
4  1999-03-31  18.28  18.59  18.26  18.02   1406700.0    25762359.0   

   fuquan_factor  
0            1.0  
1            1.0  
2            1.0  
3            1.0  
4            1.0  
3910


In [209]:
print data_df1.loc[900:1500,:]

            date    open    high   close     low     volume  trade_amount  \
900   2003-01-08  17.572  18.077  18.011  17.572   377953.0     5067600.0   
901   2003-01-09  17.944  18.928  18.503  17.811  1675296.0    23273874.0   
902   2003-01-10  18.596  19.393  18.649  18.356  2845311.0    40642774.0   
903   2003-01-13  18.542  19.194  18.835  18.529  1027767.0    14611761.0   
904   2003-01-14  18.875  19.845  19.699  18.755  2981627.0    43689918.0   
905   2003-01-15  19.672  20.204  19.380  19.207  2290993.0    34070247.0   
906   2003-01-16  19.420  19.792  19.619  19.313  1199587.0    17643760.0   
907   2003-01-17  19.686  20.098  19.739  19.566  1406745.0    20945465.0   
908   2003-01-20  19.726  20.018  19.752  19.340   931551.0    13765127.0   
909   2003-01-21  19.898  20.138  19.300  19.287  1494668.0    22258942.0   
910   2003-01-22  19.300  19.486  19.220  19.021   819966.0    11855414.0   
911   2003-01-23  19.220  19.606  19.101  19.088   569485.0     8246859.0   

In [170]:
data_df1.loc[97:100,:]

date  open   high  close    low    volume  trade_amount  \
97   1999-08-10  30.6  30.90  30.80  28.01  652900.0    19389230.0   
98   1999-08-11  30.4  30.40  29.62  29.42  350100.0    10393410.0   
99   1999-08-12  29.7  29.80  29.72  29.00  447200.0    13123773.0   
100  1999-08-13  29.7  29.75  29.60  29.49  299000.0     8851274.0   

     fuquan_factor  
97             1.0  
98             1.0  
99             1.0  
100            1.0

In [162]:
y1=data_df1.close


0        18.990
1        18.260
2        18.010
3        18.290
4        18.260
5        17.710
6        17.720
7        18.180
8        17.890
9        17.550
10       17.460
11       17.010
12       16.650
13       16.880
14       16.940
15       17.290
16       17.230
17       16.850
18       16.960
19       16.530
20       17.180
21       17.010
22       15.680
23       15.590
24       16.010
25       16.130
26       16.000
27       15.990
28       16.230
29       16.920
         ...   
3880    125.336
3881    126.356
3882    125.571
3883    123.609
3884    123.923
3885    123.452
3886    122.118
3887    122.354
3888    122.511
3889    118.273
3890    118.116
3891    119.214
3892    119.842
3893    119.685
3894    119.450
3895    111.916
3896    112.543
3897    110.503
3898    111.288
3899    114.427
3900    113.250
3901    113.721
3902    114.035
3903    112.857
3904    110.974
3905    111.131
3906    111.209
3907    110.424
3908    110.503
3909    112.936
Name: close, Length: 391

In [352]:
from sklearn import preprocessing  
ii=1000
train_sample=3
X=[]
for i in range(0,ii-train_sample+1):
    df1=data_df1.loc[i:i+2,['open','high','close','low']]
    train_data = np.array(df1)
    train_data1=np.hstack(train_data)
    X.append(train_data1.tolist())
len(X)
#print data_df1.loc[0:2,['open','high','close','low','volume']]
#print data_df1.loc[1:3,['open','high','close','low','volume']]
X1=preprocessing.scale(X)  


In [361]:
import random
rand1=random.sample(xrange(998),800)
X=X1[rand1]
y5=y4[rand1]
clf = svm.SVC(C=0.9, kernel='rbf', gamma=20, decision_function_shape='ovr')
clf.fit(X, y5)  
print clf.score(X, y5)

0.76875


In [355]:
y2=y1.diff(periods=1)
#print y2[train_sample:ii+1]
y3=y2.loc[train_sample:ii,]
y3=np.array(y3)
y4=np.int64(y3>0)
print len(y4)
X=X1[0:800]
#print X
y5=y4[0:800]
clf = svm.SVC(C=0.8, kernel='rbf', gamma=20, decision_function_shape='ovr')
clf.fit(X, y5)  
print clf.score(X, y5)


998
0.77375


In [362]:
print len(X1)
prd=[]
act=[]
for i in range(900,995):
    df1=X1[i]
    prd1=clf.predict([df1.tolist()])
    prd.append(prd1[0])
    act.append(y2[i])
print prd

a2=np.array(act)
a2[a2>0]=1
a2[a2<0]=0
print a2
a3=a2.tolist()
dif1=np.subtract(prd, a3)
np.sum(np.square(dif1))/96

998
[1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1]
[ 1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.  0.  1.  1.  1.  0.  0.  1.
  1.  0.  0.  0.  1.  1.  0.  0.  0.  1.  1.  0.  0.  1.  1.  0.  1.  1.
  0.  1.  1.  0.  0.  0.  0.  1.  0.  1.  1.  0.  0.  1.  0.  1.  1.  1.
  0.  1.  0.  0.  1.  1.  1.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.
  0.  0.  0.  0.  1.  1.  0.  1.  0.  1.  0.  1.  0.  1.  1.  1.  1.  0.
  0.  0.  0.  0.  1.]


0.51041666666666663

In [291]:
X1[902]

array([-1.2315453 , -1.18027655, -1.22589777, -1.23085968,  1.00087197,
       -1.23716567, -1.20127956, -1.20503136, -1.21092899, -0.07527618,
       -1.20015919, -1.13026108, -1.10939415, -1.18531992,  1.37816215])

In [284]:
df1

array([-1.34460717, -1.32323831, -1.29647699, -1.31961268, -0.46627371,
       -1.30318095, -1.23016736, -1.2417538 , -1.29219649,  0.39817428,
       -1.23095519, -1.17934052, -1.22553007, -1.23048045,  1.27709385])

In [196]:
a1=clf.predict([train_data1.tolist()])
a1[0]

0

In [ ]:
clf.predict([[2., 2.]])


In [101]:
len(result)

100

In [97]:
len(result)
y2=[0,0,1]
clf = svm.SVC()
clf.fit(result, y2)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
y1=data_df1.open
y2=y1.diff(periods=1)
print y2

In [41]:
df1=data_df1.loc[:,['open','high','close','volume']]
#df1
train_data = np.array(df1)
y1=data_df1.open-data_df1.close
y2=np.array(y1)
#map(lambda x:[0 if x<0 for i in x],y2)
y3=np.int64(y2>0)




[[  1.90100000e+01   2.03800000e+01   1.89900000e+01   3.20648000e+07]
 [  1.89000000e+01   1.94600000e+01   1.82600000e+01   8.32260000e+06]
 [  1.82000000e+01   1.84700000e+01   1.80100000e+01   3.94530000e+06]
 ..., 
 [  1.11288000e+02   1.11523000e+02   1.10424000e+02   7.17736900e+06]
 [  1.10189000e+02   1.11759000e+02   1.10503000e+02   7.00538600e+06]
 [  1.10660000e+02   1.14427000e+02   1.12936000e+02   1.82479040e+07]]


In [54]:
clf = svm.SVC()
clf.fit(train_data, y3)  
clf.predict([[3,4,10,22222]])


array([0], dtype=int64)

In [18]:
import numpy as np
from sklearn.datasets import dump_svmlight_file

X = data_df1[np.setdiff1d(data_df1.columns,['open','close','date'])]
#print X
y = data_df1.fuquan_factor
dump_svmlight_file(X,y,'smvlight.dat',zero_based=True,multilabel=False)


In [27]:
import pandas as pd
df = pd.DataFrame({"x": ['011', '100', '111'] , "y": [0,1,0]})
df
data_df1

date     open     high    close      low      volume  \
0     1999-03-25   19.010   20.380   18.990   18.900  32064800.0   
1     1999-03-26   18.900   19.460   18.260   18.020   8322600.0   
2     1999-03-29   18.200   18.470   18.010   17.710   3945300.0   
3     1999-03-30   18.050   18.550   18.290   17.750   2168600.0   
4     1999-03-31   18.280   18.590   18.260   18.020   1406700.0   
5     1999-04-01   18.070   18.180   17.710   17.600   2363200.0   
6     1999-04-02   18.000   18.000   17.720   17.290   2223200.0   
7     1999-04-05   17.750   18.200   18.180   17.630   1237900.0   
8     1999-04-06   18.100   18.450   17.890   17.850   1284800.0   
9     1999-04-07   17.850   18.070   17.550   17.500    931200.0   
10    1999-04-08   17.500   17.690   17.460   17.300   1070800.0   
11    1999-04-09   17.420   17.520   17.010   16.990   1247200.0   
12    1999-04-12   17.000   17.000   16.650   16.500   1083900.0   
13    1999-04-13   16.520   17.100   16.880   16.520    768200.0   
14    1999-04-14   16.780   17.100   16.940   16.680    377200.0   
15    1999-04-15   16.880   17.650   17.290   16.550   1253000.0   
16    1999-04-16   17.280   17.390   17.230   17.010    359800.0   
17    1999-04-19   17.210   17.210   16.850   16.710    461800.0   
18    1999-04-20   16.570   17.150   16.960   16.570    188600.0   
19    1999-04-21   16.850   17.070   16.530   16.500    332700.0   
20    1999-04-22   16.500   17.960   17.180   16.460   1216400.0   
21    1999-04-23   17.310   17.310   17.010   16.800    349500.0   
22    1999-04-26   16.800   16.870   15.680   15.600   1395100.0   
23    1999-04-27   15.560   16.090   15.590   15.400   1024800.0   
24    1999-04-28   15.650   17.090   16.010   15.650   1473000.0   
25    1999-04-29   15.990   16.180   16.130   15.680    422200.0   
26    1999-04-30   16.000   16.390   16.000   15.890    247100.0   
27    1999-05-04   16.800   16.800   15.990   15.960    386200.0   
28    1999-05-05   16.000   16.400   16.230   15.810    445500.0   
29    1999-05-06   16.300   17.500   16.920   16.120   2426300.0   
...          ...      ...      ...      ...      ...         ...   
3880  2016-11-21  125.571  126.356  125.336  124.943  12834457.0   
3881  2016-11-22  125.336  126.435  126.356  125.336  16337999.0   
3882  2016-11-23  126.356  126.749  125.571  125.414  17858329.0   
3883  2016-11-24  125.414  125.728  123.609  123.295  24415755.0   
3884  2016-11-25  124.002  124.080  123.923  121.647  23755195.0   
3885  2016-11-28  124.002  125.493  123.452  123.217  25702158.0   
3886  2016-11-29  123.138  124.080  122.118  121.804  19232352.0   
3887  2016-11-30  121.804  123.138  122.354  121.726  15683765.0   
3888  2016-12-01  122.354  122.903  122.511  121.883  11945190.0   
3889  2016-12-02  122.275  122.511  118.273  117.959  29870472.0   
3890  2016-12-05  117.566  118.822  118.116  116.938  13953079.0   
3891  2016-12-06  118.116  120.548  119.214  117.723  18927784.0   
3892  2016-12-07  119.057  120.235  119.842  118.273  13408046.0   
3893  2016-12-08  120.313  120.705  119.685  119.293  12128395.0   
3894  2016-12-09  119.999  120.156  119.450  119.057  11703234.0   
3895  2016-12-12  119.528  119.764  111.916  111.759  23972923.0   
3896  2016-12-13  111.837  114.034  112.543  111.758  13077758.0   
3897  2016-12-14  112.622  112.779  110.503  110.346  13039490.0   
3898  2016-12-15  110.267  112.386  111.288  110.189   9062249.0   
3899  2016-12-16  112.308  115.604  114.427  112.308  21011387.0   
3900  2016-12-19  114.662  114.662  113.250  112.936   7097483.0   
3901  2016-12-20  113.093  113.956  113.721  113.014   6883130.0   
3902  2016-12-21  114.192  114.898  114.035  113.721   6905417.0   
3903  2016-12-22  113.485  113.799  112.857  112.700   6989495.0   
3904  2016-12-23  112.779  112.779  110.974  110.817   7978304.0   
3905  2016-12-26  110.503  111.445  111.131  109.326   8449496.0   
3906  2016-12-27  111.680  112.622  111.209  110.974   8293400.0   


In [29]:
data_df1.x.apply(lambda x: np.array(list(map(int,close))))


AttributeError: 'DataFrame' object has no attribute 'x'

In [38]:
from sklearn import svm
X = [[0, 0], [1, 1]]
y = [0, 1]
clf = svm.SVC()
clf.fit(X, y)  
type(X)


list

In [5]:
clf.predict([[2., 2.]])


array([1])